In [1]:
import math

import numpy as np
from math import sqrt


In [2]:
semi_minor = 5003
semi_major = 12003

Q = np.diag([
    1/semi_minor**2,
    1/semi_major**2,
    1/semi_minor**2,
    -1
])
Q

array([[ 3.99520432e-08,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  6.94097352e-09,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  3.99520432e-08,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+00]])

In [32]:
E_plane = np.array([
    [0, 1, 0],
    [0, 0, semi_major-1],
    [1, 0, 0],
    [0, 0, 1]
])

E_plane

array([[    0,     1,     0],
       [    0,     0, 12002],
       [    1,     0,     0],
       [    0,     0,     1]])

In [33]:
C = np.linalg.matrix_transpose(E_plane) @ Q @ E_plane
C

array([[ 3.99520432e-08,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  3.99520432e-08,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -1.66618069e-04]])

In [34]:
np.linalg.det(C)

np.float64(-2.65950056287622e-19)

In [35]:
np.linalg.det(C[:2,:2])

np.float64(1.5961657530952494e-15)

In [36]:
scale_sphere_down = np.diag([1/semi_minor, 1/semi_major, 1/semi_minor, 1])

E_plane_scaled = scale_sphere_down @ E_plane
E_plane_scaled

array([[0.00000000e+00, 1.99880072e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 9.99916687e-01],
       [1.99880072e-04, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [37]:
plane_norm_scaled = np.linalg.cross(E_plane_scaled[:3, 0], E_plane_scaled[:3, 1])
plane_norm_scaled

array([0.00000000e+00, 3.99520432e-08, 0.00000000e+00])

In [38]:
plane_d = plane_norm_scaled @ E_plane_scaled[:3, 2]
plane_d

np.float64(3.994871466066165e-08)

In [39]:
plane_distance = abs(plane_d) / np.linalg.norm(plane_norm_scaled)
plane_distance

np.float64(0.9999166874947929)

In [40]:
plane_d ** 2

np.float64(1.595899803038963e-15)

In [41]:
plane_d ** 2 < plane_norm_scaled @  plane_norm_scaled

np.True_

In [42]:
def greater_than_or_close(x: float, y: float) -> bool:
    return x > y or math.isclose(x, y)

In [43]:
not greater_than_or_close(abs(plane_d), np.linalg.norm(plane_norm_scaled))

True